version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Setting Gradle Permission
          command: chmod +x gradlew
      - run:
          name: Building
          command: ./gradlew build
